apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: dotnet-1-redis-1 
        image: nithu99/dotnet-1-redis-1
        ports:
        - containerPort: 80